<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Intencao;
use Illuminate\Database\Seeder;

class IntencoesSeeder extends Seeder
{
    public function run(): void
    {
        $intencoes = [
            [
                'intencao_id' => 'servicos_municipais',
                'resposta' => 'Bem-vindo ao Portal da Prefeitura de Assaí! Você pode consultar informações sobre serviços municipais, agendamentos, certidões, alvarás, licitações e muito mais. Como posso ajudá-lo?',
                'contexto' => 'Serviços municipais oferecidos pela prefeitura incluem emissão de certidões, agendamentos de atendimento, protocolos de denúncia e informações sobre órgãos públicos.',
                'triggers' => [
                    'serviço', 'serviços', 'prefeitura', 'municipal', 'ajuda',
                    'pode me ajudar', 'preciso de', 'como faço',
                ],
                'prioridade' => 100,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'geral', 'tags' => ['serviços', 'informação']],
            ],
            [
                'intencao_id' => 'saudacao',
                'resposta' => 'Olá! Bem-vindo ao Portal da Prefeitura de Assaí. Como posso ajudá-lo hoje?',
                'contexto' => 'Saudações iniciais para começar uma conversa de forma amigável e acessível.',
                'triggers' => [
                    'olá', 'oi', 'opa', 'e aí', 'como vai', 'bom dia', 'boa tarde', 'boa noite',
                ],
                'prioridade' => 10,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'saudação', 'tags' => ['saudação', 'cumprimento']],
            ],
            [
                'intencao_id' => 'obrigado',
                'resposta' => 'De nada! Fico feliz em ajudar. Se tiver mais dúvidas, é só falar!',
                'contexto' => 'Resposta de agradecimento de forma educada e amigável.',
                'triggers' => [
                    'obrigado', 'muito obrigado', 'brigadão', 'thanks', 'vlw', 'flw', 'valeu',
                ],
                'prioridade' => 5,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'saudação', 'tags' => ['agradecimento']],
            ],
            [
                'intencao_id' => 'despedida',
                'resposta' => 'Até logo! Tenha um ótimo dia!',
                'contexto' => 'Despedida cordial de uma conversa.',
                'triggers' => [
                    'adeus', 'tchau', 'falou', 'até mais', 'até breve', 'até logo', 'bye',
                ],
                'prioridade' => 5,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'saudação', 'tags' => ['despedida']],
            ],
            [
                'intencao_id' => 'prefeitura_assai',
                'resposta' => 'O site oficial da Prefeitura de Assaí é <a href="https://www.assai.pr.gov.br" target="_blank">www.assai.pr.gov.br</a>. Lá você encontra notícias, estrutura administrativa, telefones úteis e a Carta de Serviços. O atendimento presencial é na Av. Rio de Janeiro, 720, Centro, de segunda a sexta, das 8h às 11h30 e das 13h às 17h. Telefone: (43) 3262-1313. E-mail: assai@assai.pr.gov.br.',
                'contexto' => 'Prefeitura de Assaí: site oficial com notícias, serviços e informações institucionais.',
                'triggers' => [
                    'prefeitura', 'assai', 'assaí', 'município', 'prefeito', 'tuti', 'bomtempo',
                    'site da prefeitura', 'portal da prefeitura', 'endereço da prefeitura', 'telefone da prefeitura',
                ],
                'prioridade' => 92,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'portais', 'tags' => ['prefeitura', 'oficial', 'contato']],
            ],
            [
                'intencao_id' => 'conecta_assai',
                'resposta' => 'O <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> é o portal oficial de serviços digitais da Prefeitura. Por ele você pode emitir certidões, consultar licitações, acessar o Diário Oficial, inscrever-se em editais, acompanhar protocolos e muito mais. Qual serviço específico você procura?',
                'contexto' => 'Conecta Assaí: portal de serviços digitais. Serviços principais: emissão de guia de alvará, certidões fiscais, Portal da Transparência, licitações, Diário Oficial, Cidadão Web, etc.',
                'triggers' => [
                    'conecta', 'conecta assaí', 'portal de serviços', 'serviços online', 'betha', 'cidadão web',
                    'site conecta', 'acessar conecta',
                ],
                'prioridade' => 88,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'portais', 'tags' => ['conecta', 'serviços digitais', 'portal']],
            ],
            [
                'intencao_id' => 'gov_assai',
                'resposta' => 'O <a href="https://gov.assai.pr.gov.br" target="_blank">Gov.Assaí</a> é o sistema de identidade digital do município. Com uma única conta (CPF e senha) você acessa todos os serviços públicos online de forma unificada, além de ter acesso a vantagens como o Passaporte Estudantil e inscrições em oficinas culturais. Para serviços que exigem maior segurança, é necessário realizar o cadastro de Nível 2.',
                'contexto' => 'Gov.Assaí: plataforma de identidade digital. Necessário cadastro de Nível 2 para acessar todos os serviços.',
                'triggers' => [
                    'gov assaí', 'gov assai', 'identidade digital', 'login', 'cadastro', 'passaporte estudantil',
                    'gov.br', 'acessar gov', 'registro gov',
                ],
                'prioridade' => 86,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'portais', 'tags' => ['gov', 'identidade', 'acesso']],
            ],
            [
                'intencao_id' => 'vale_do_sol',
                'resposta' => 'O <a href="https://valedosol.assai.pr.gov.br" target="_blank">Vale do Sol</a> é o ecossistema de inovação de Assaí. Ele conecta governo, empresas e instituições de ensino para promover empreendedorismo, cursos, coworking, turismo e soluções inteligentes para a cidade. A agência fica na Rua Edgar Bardal e atende de segunda a sexta, das 8h às 11h30 e das 13h às 17h. Telefone: (43) 3262-8306.',
                'contexto' => 'Vale do Sol: ecossistema de inovação que oferece apoio a startups e empreendedores, cursos, espaços de coworking, turismo e sustentabilidade.',
                'triggers' => [
                    'vale do sol', 'inovação', 'startup', 'empreendedorismo', 'coworking', 'agência de inovação',
                    'onde fica o vale do sol', 'telefone vale do sol',
                ],
                'prioridade' => 82,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'portais', 'tags' => ['inovação', 'empreendedorismo', 'tecnologia']],
            ],
            [
                'intencao_id' => 'jornal_asahi',
                'resposta' => 'O <a href="https://www.jornalasahi.com.br" target="_blank">Jornal Asahi</a> é o primeiro jornal de Assaí produzido 100% por estudantes do ensino fundamental e médio. Ele traz notícias, cultura e eventos locais, sendo uma iniciativa de incentivo à educação e à comunicação jovem na cidade. Quer saber sobre alguma notícia específica?',
                'contexto' => 'Jornal Asahi: jornal municipal feito por estudantes. Cobre notícias, cultura e eventos de Assaí.',
                'triggers' => [
                    'jornal', 'asahi', 'assahi', 'notícia', 'estudantes', 'jovem', 'jornal escolar',
                ],
                'prioridade' => 65,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'portais', 'tags' => ['jornal', 'notícias', 'educação']],
            ],
            [
                'intencao_id' => 'certidoes',
                'resposta' => 'Para solicitar certidões municipais, acesse o <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a>. Você pode emitir online a Certidão Negativa de Débitos (CND), Certidão Positiva com Efeitos de Negativa (CPEND) e a Certidão de Inscrição Municipal. O serviço é válido para CPF, CNPJ, imóvel rural (NIRF) ou obra (CNO). Qual tipo de certidão você precisa?',
                'contexto' => 'Certidões municipais incluem certidão de negativa de débitos, certidão de negativa de infrações, certidão de propriedade de imóvel. Emissão online pelo Conecta Assaí.',
                'triggers' => [
                    'certidão', 'certidões', 'negativa', 'debitos', 'dívida', 'emissão',
                    'como emitir certidão', 'certidão municipal', 'tirar certidão',
                ],
                'prioridade' => 90,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'certidões', 'tags' => ['certidão', 'negativa', 'débito']],
            ],
            [
                'intencao_id' => 'certidoes_assai',
                'resposta' => 'Você pode emitir certidões de regularidade fiscal pelo <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a>. Estão disponíveis a Certidão Negativa de Débitos (CND), a Certidão Positiva com Efeitos de Negativa (CPEND) e a Certidão de Inscrição Municipal. O serviço é online e válido para CPF, CNPJ, imóvel rural (NIRF) ou obra (CNO).',
                'contexto' => 'Emissão de certidões fiscais pelo Conecta Assaí. Opções: CND, CPEND, CPD.',
                'triggers' => [
                    'certidão negativa', 'certidão positiva', 'regularidade fiscal', 'inscrição municipal',
                    'cnd', 'cpd', 'certidão municipal',
                ],
                'prioridade' => 89,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'certidões', 'tags' => ['certidão', 'fiscal', 'regularidade']],
            ],
            [
                'intencao_id' => 'alvaras',
                'resposta' => 'Para solicitar alvarás (funcionamento, localização, construção, sanitário, ambiental), acesse o <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a>. O processo é totalmente online para o alvará de localização e funcionamento. Para alvarás específicos como o sanitário, é necessário contatar a <strong>Vigilância Sanitária</strong>, vinculada à Secretaria Municipal de Saúde. Qual tipo de alvará você precisa?',
                'contexto' => 'Alvarás municipais incluem alvará de funcionamento, localização, construção, sanitário e ambiental. Emissão online pelo Conecta Assaí.',
                'triggers' => [
                    'alvará', 'alvarás', 'alvara', 'alvaras', 'funcionamento', 'localização', 'construção', 'autorização',
                    'como tirar alvará', 'pedir alvará',
                ],
                'prioridade' => 85,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'alvarás', 'tags' => ['alvará', 'funcionamento', 'autorização']],
            ],
            [
                'intencao_id' => 'alvara_assai',
                'resposta' => 'Para emitir o Alvará de Localização e Funcionamento, acesse o <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> e utilize o serviço "Acessar Guia de Alvará" no portal Betha Cidadão Web. O processo é totalmente online, eliminando a necessidade de deslocamento até a prefeitura.',
                'contexto' => 'Emissão de guia de alvará de localização e funcionamento pelo portal Betha Cidadão Web.',
                'triggers' => [
                    'alvará de funcionamento', 'alvará de localização', 'guia de alvará',
                    'emitir guia de alvará', 'alvará online', 'tirar alvará rápido',
                ],
                'prioridade' => 87,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'alvarás', 'tags' => ['alvará', 'funcionamento', 'online']],
            ],
            [
                'intencao_id' => 'vigilancia_sanitaria',
                'resposta' => 'O <strong>Alvará Sanitário</strong> e demais licenças da <strong>Vigilância Sanitária</strong> são de responsabilidade da Secretaria Municipal de Saúde. Para solicitar, entre em contato pelo telefone (43) 3262-8405 ou acesse o <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> e procure pelos serviços da Vigilância Sanitária. O atendimento presencial é na sede da Secretaria de Saúde.',
                'contexto' => 'Alvará Sanitário e Vigilância Sanitária de Assaí. Subordinada à Secretaria de Saúde. Tel: (43) 3262-8405.',
                'triggers' => [
                    'vigilância sanitária', 'alvará sanitário', 'sanitário', 'vigilancia sanitaria',
                ],
                'prioridade' => 84,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'saúde', 'tags' => ['vigilância', 'alvará sanitário']],
            ],
            [
                'intencao_id' => 'diario_oficial',
                'resposta' => 'O Diário Oficial Eletrônico de Assaí publica leis, decretos, licitações e portarias municipais. Você pode consultar as edições recentes e filtrar por período, departamento ou tipo de publicação. Acesse em <a href="https://www.doemunicipal.com.br/prefeituras/4" target="_blank">doemunicipal.com.br/prefeituras/4</a>.',
                'contexto' => 'Diário Oficial do Município de Assaí. Publicações oficiais de atos administrativos.',
                'triggers' => [
                    'diário oficial', 'diario oficial', 'publicação', 'lei', 'decreto', 'portaria',
                    'acessar diário oficial', 'consultar diário oficial',
                ],
                'prioridade' => 78,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'documentos', 'tags' => ['diário oficial', 'publicações', 'leis']],
            ],
            [
                'intencao_id' => 'portal_transparencia',
                'resposta' => 'O Portal da Transparência de Assaí está disponível em <a href="https://transparencia.betha.cloud" target="_blank">transparencia.betha.cloud</a>. Lá você encontra receitas, despesas, repasses, contratos e licitações do município. A consulta é pública e gratuita, sem necessidade de cadastro.',
                'contexto' => 'Portal da Transparência da Prefeitura de Assaí. Acesso público a informações financeiras e licitações.',
                'triggers' => [
                    'transparência', 'portal da transparência', 'betha', 'receitas', 'despesas', 'orçamento',
                    'acessar transparência', 'consultar gastos', 'gastos públicos',
                ],
                'prioridade' => 76,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'transparência', 'tags' => ['transparência', 'orçamento', 'licitações']],
            ],
            [
                'intencao_id' => 'licitacoes_assai',
                'resposta' => 'As licitações da Prefeitura de Assaí podem ser acompanhadas no <a href="https://transparencia.betha.cloud" target="_blank">Portal da Transparência Betha</a>. Você encontra processos nas modalidades dispensa, pregão eletrônico, pregão presencial e concorrência. É possível filtrar por número, modalidade, ano e situação do processo.',
                'contexto' => 'Licitações municipais de Assaí. Disponíveis no Portal da Transparência Betha.',
                'triggers' => [
                    'licitação', 'licitações', 'pregão', 'concorrência', 'dispensa', 'edital', 'processo licitatório',
                    'acompanhar licitação', 'ver editais de licitação',
                ],
                'prioridade' => 84,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'licitações', 'tags' => ['licitações', 'pregão', 'concorrência']],
            ],
            [
                'intencao_id' => 'agendamentos',
                'resposta' => 'Você pode realizar agendamentos de atendimento diretamente no <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> ou entrando em contato com a secretaria desejada. Oferecemos agendamentos para atendimentos na Prefeitura, Câmara Municipal e secretarias. Qual serviço você gostaria de agendar?',
                'contexto' => 'Agendamentos podem ser realizados online ou por telefone. Os horários variam de acordo com a secretaria. Agendamentos normalmente são confirmados em até 24 horas.',
                'triggers' => [
                    'agendar', 'agendamento', 'marcar', 'horário', 'data', 'consulta', 'atendimento',
                    'como agendar', 'agendar atendimento', 'marcar consulta',
                ],
                'prioridade' => 95,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'agendamentos', 'tags' => ['agenda', 'consulta', 'atendimento']],
            ],
            [
                'intencao_id' => 'ouvidoria_assai',
                'resposta' => 'A Ouvidoria Municipal de Assaí é o canal para registrar sugestões, elogios, reclamações e denúncias. Você pode acessar pelo site <a href="https://www.assai.pr.gov.br/ouvidoria" target="_blank">assai.pr.gov.br/ouvidoria</a>, pelo e-mail ouvidoria@assai.pr.gov.br ou pelo telefone (43) 3262-1313. O atendimento presencial é na Av. Rio de Janeiro, 720, Centro.',
                'contexto' => 'Ouvidoria Municipal de Assaí. Canal para manifestações, denúncias e reclamações.',
                'triggers' => [
                    'ouvidoria', 'reclamação', 'sugestão', 'elogio', 'denúncia', 'manifestação',
                    'falar na ouvidoria', 'registrar denúncia', 'canal de denúncia',
                ],
                'prioridade' => 83,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'atendimento', 'tags' => ['ouvidoria', 'reclamação', 'denúncia']],
            ],
            [
                'intencao_id' => 'denuncia',
                'resposta' => 'Você pode fazer uma denúncia através da <a href="https://www.assai.pr.gov.br/ouvidoria" target="_blank">Ouvidoria Municipal</a> (anônimo ou identificado), ou comparecer pessoalmente à Prefeitura. Aceitamos denúncias sobre infrações administrativas, irregularidades e problemas municipais. Gostaria de fazer uma denúncia?',
                'contexto' => 'Denúncias podem ser anônimas ou identificadas. Todas as denúncias são investigadas e sigilosas. O prazo de resposta é de até 30 dias úteis.',
                'triggers' => [
                    'denúncia', 'denunciar', 'reclamação', 'problema', 'irregular', 'ilegal', 'infração',
                    'fazer denúncia', 'onde denunciar',
                ],
                'prioridade' => 80,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'denúncias', 'tags' => ['denuncia', 'infração', 'reclamação']],
            ],
            [
                'intencao_id' => 'contato',
                'resposta' => 'Você pode entrar em contato com a Prefeitura de Assaí pelo telefone (43) 3262-1313, pelo e-mail assai@assai.pr.gov.br ou pelo site oficial <a href="https://www.assai.pr.gov.br" target="_blank">www.assai.pr.gov.br</a>. O atendimento presencial funciona de segunda a sexta, das 8h às 11h30 e das 13h às 17h, na Av. Rio de Janeiro, 720, Centro.',
                'contexto' => 'Contato da Prefeitura de Assaí. Telefone: (43) 3262-1313. Email: assai@assai.pr.gov.br.',
                'triggers' => [
                    'contato', 'telefone', 'email', 'falar com', 'comunicar', 'endereço', 'horário',
                    'whatsapp da prefeitura', 'como falar com a prefeitura', 'ligar para prefeitura',
                ],
                'prioridade' => 72,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'contato', 'tags' => ['contato', 'comunicação', 'endereço']],
            ],
            [
                'intencao_id' => 'secretarias',
                'resposta' => 'A Prefeitura de Assaí possui as seguintes secretarias:<ul><li><strong>Saúde:</strong> Dylan Custódio | (43) 3262-8405 | saude@assai.pr.gov.br</li><li><strong>Educação:</strong> Josiane Cheffer | (43) 3262-1240</li><li><strong>Obras e Serviços:</strong> Orlando Menegazzo Filho | (43) 3262-0089 | obras@assai.pr.gov.br</li><li><strong>Assistência Social:</strong> Vera Lucia Manoel Lourenço | (43) 3262-1223 | smas@assai.pr.gov.br</li><li><strong>Finanças:</strong> (43) 3262-1313</li><li><strong>Esporte e Lazer:</strong> (43) 3262-1964</li><li><strong>Cultura e Turismo:</strong> Yashiro Imazu | (43) 3262-3232</li><li><strong>Segurança Alimentar e Nutrição:</strong> Margareth Ferreira | (43) 3262-4349</li></ul>',
                'contexto' => 'Estrutura administrativa da Prefeitura de Assaí. Lista de secretarias com responsáveis e contatos.',
                'triggers' => [
                    'secretaria', 'secretarias', 'órgãos', 'administração', 'estrutura',
                    'quais as secretarias', 'telefone das secretarias',
                ],
                'prioridade' => 80,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'secretarias', 'tags' => ['secretarias', 'administração']],
            ],
            [
                'intencao_id' => 'secretaria_saude',
                'resposta' => 'A <strong>Secretaria Municipal de Saúde</strong> é responsável pela gestão do Hospital Municipal, Unidades Básicas de Saúde (UBS), Farmácia Municipal e Vigilância Sanitária. Responsável: Dylan Custódio. E-mail: saude@assai.pr.gov.br. Telefone: (43) 3262-8405. Para agendar consultas, você pode enviar mensagem via WhatsApp para a UBS mais próxima da sua casa.',
                'contexto' => 'Secretaria Municipal de Saúde de Assaí. Responsável: Dylan Custódio.',
                'triggers' => [
                    'saúde', 'secretaria de saúde', 'hospital', 'posto de saúde', 'ubs',
                    'onde fica a secretaria de saúde', 'contato secretaria de saúde',
                ],
                'prioridade' => 85,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'secretarias', 'tags' => ['saúde', 'secretaria']],
            ],
            [
                'intencao_id' => 'secretaria_educacao',
                'resposta' => 'A <strong>Secretaria Municipal de Educação</strong> é responsável pela rede municipal de ensino, incluindo escolas e CMEIs. Responsável: Josiane Cheffer (secretária). Telefone: (43) 3262-1240. A secretaria também coordena o programa de ensino bilíngue e oficinas extracurriculares.',
                'contexto' => 'Secretaria Municipal de Educação de Assaí. Responsável: Josiane Cheffer.',
                'triggers' => [
                    'educação', 'secretaria de educação', 'escola', 'escolas', 'cmei',
                    'onde fica a secretaria de educação', 'contato secretaria de educação',
                ],
                'prioridade' => 85,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'secretarias', 'tags' => ['educação', 'secretaria']],
            ],
            [
                'intencao_id' => 'secretaria_obras',
                'resposta' => 'A <strong>Secretaria de Obras e Serviços</strong> é responsável pela manutenção de vias, prédios públicos e infraestrutura urbana. Responsável: Orlando Menegazzo Filho. E-mail: obras@assai.pr.gov.br. Telefone: (43) 3262-0089.',
                'contexto' => 'Secretaria de Obras e Serviços de Assaí. Responsável: Orlando Menegazzo Filho.',
                'triggers' => [
                    'obras', 'secretaria de obras', 'infraestrutura', 'manutenção',
                    'onde fica a secretaria de obras', 'contato secretaria de obras',
                ],
                'prioridade' => 80,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'secretarias', 'tags' => ['obras', 'secretaria']],
            ],
            [
                'intencao_id' => 'secretaria_assistencia',
                'resposta' => 'A <strong>Secretaria Municipal de Assistência Social</strong> é responsável pelos programas sociais, CRAS (Centro de Referência de Assistência Social) e atendimento a famílias em vulnerabilidade. Responsável: Vera Lucia Manoel Lourenço. E-mail: smas@assai.pr.gov.br. Telefone: (43) 3262-1223.',
                'contexto' => 'Secretaria Municipal de Assistência Social de Assaí.',
                'triggers' => [
                    'assistência social', 'secretaria de assistência', 'social', 'cras',
                    'onde fica a assistência social', 'contato assistência social',
                ],
                'prioridade' => 85,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'secretarias', 'tags' => ['assistência', 'social', 'secretaria']],
            ],
            [
                'intencao_id' => 'secretaria_cultura',
                'resposta' => 'A <strong>Secretaria de Cultura e Turismo</strong> (SECUT) promove eventos culturais, turísticos e cuida do patrimônio histórico. O secretário atual é Yashiro Imazu. Telefone: (43) 3262-3232. Endereço: Castelo Japonês.',
                'contexto' => 'Secretaria de Cultura e Turismo de Assaí. Responsável: Yashiro Imazu.',
                'triggers' => [
                    'cultura', 'turismo', 'secretaria de cultura', 'eventos',
                    'onde fica a secretaria de cultura', 'contato cultura',
                ],
                'prioridade' => 80,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'secretarias', 'tags' => ['cultura', 'turismo', 'secretaria']],
            ],
            [
                'intencao_id' => 'hospital_municipal',
                'resposta' => 'O <strong>Hospital Municipal de Assaí</strong> oferece atendimento 24 horas com Pronto-Socorro e internações. Endereço: Rua Manoel Ribas, 1580, Centro. Telefone: (43) 3262-4080. O hospital conta com equipe de enfermagem completa e médicos plantonistas.',
                'contexto' => 'Hospital Municipal de Assaí: pronto-socorro 24h, internações.',
                'triggers' => [
                    'hospital', 'pronto socorro', 'pronto-socorro', 'emergência', 'urgência',
                    'onde fica o hospital', 'telefone do hospital', 'hospital municipal',
                ],
                'prioridade' => 88,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'saúde', 'tags' => ['hospital', 'emergência']],
            ],
            [
                'intencao_id' => 'ubs',
                'resposta' => 'As Unidades Básicas de Saúde (UBS) de Assaí realizam atendimento primário, vacinação e acompanhamento de saúde da família. A UBS Central fica na Rua Manoel Ribas, 1791, telefone (43) 3262-8400. O agendamento de consultas pode ser feito via WhatsApp. Consulte os números atualizados no site da prefeitura.',
                'contexto' => 'Unidades Básicas de Saúde de Assaí. UBS Central: Rua Manoel Ribas, 1791.',
                'triggers' => [
                    'ubs', 'unidade básica', 'posto de saúde', 'postinho', 'vacina',
                    'onde fica a ubs', 'endereço da ubs', 'telefone da ubs',
                ],
                'prioridade' => 86,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'saúde', 'tags' => ['ubs', 'posto de saúde', 'vacinação']],
            ],
            [
                'intencao_id' => 'farmacia_municipal',
                'resposta' => 'A <strong>Farmácia Municipal</strong> dispensa medicamentos gratuitos à população. Endereço: Av. Rio de Janeiro, 1520, Centro. O abastecimento é realizado toda quinta-feira. Para retirar medicamentos, é necessário apresentar receita médica válida e documentos pessoais. O atendimento é de segunda a sexta, em horário comercial.',
                'contexto' => 'Farmácia Municipal de Assaí. Medicamentos gratuitos com receita.',
                'triggers' => [
                    'farmácia', 'remédio', 'medicamento', 'farmácia popular',
                    'onde fica a farmácia municipal', 'pegar remédio de graça',
                ],
                'prioridade' => 84,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'saúde', 'tags' => ['farmácia', 'medicamentos']],
            ],
            [
                'intencao_id' => 'saude_bucal',
                'resposta' => 'Os atendimentos odontológicos da rede pública de Assaí são oferecidos nas UBSs. Para agendar uma consulta de saúde bucal (dentista), procure a Unidade Básica de Saúde mais próxima da sua casa. Mais informações pelo telefone da Secretaria de Saúde: (43) 3262-8405.',
                'contexto' => 'Saúde Bucal em Assaí: atendimento odontológico nas UBSs. Secretaria de Saúde: (43) 3262-8405.',
                'triggers' => [
                    'dentista', 'odontológico', 'saúde bucal', 'dente', 'boca',
                    'onde tem dentista público', 'agendar dentista',
                ],
                'prioridade' => 82,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'saúde', 'tags' => ['odontologia', 'dentista']],
            ],
            [
                'intencao_id' => 'cras',
                'resposta' => 'O <strong>CRAS (Centro de Referência de Assistência Social)</strong> oferece atendimento a famílias em situação de vulnerabilidade, incluindo Cadastro Único (CadÚnico), Bolsa Família e benefícios eventuais. Endereço: Rua Equador, 427, Centro. Telefone: (43) 3262-0309.',
                'contexto' => 'CRAS de Assaí: CadÚnico, Bolsa Família, benefícios sociais.',
                'triggers' => [
                    'cras', 'cadúnico', 'bolsa família', 'benefício social', 'auxílio',
                    'onde fica o cras', 'endereço do cras', 'telefone do cras',
                    'centro de referência de assistência social', 'centro de referência',
                ],
                'prioridade' => 87,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'social', 'tags' => ['cras', 'assistência', 'cadúnico']],
            ],
            [
                'intencao_id' => 'agencia_trabalhador',
                'resposta' => 'A <strong>Agência do Trabalhador de Assaí</strong> faz a intermediação de vagas de emprego e oferece serviços como entrada no seguro-desemprego. A agência divulga vagas regularmente. Para mais informações, entre em contato com a Secretaria de Trabalho, Emprego e Geração de Renda ou acompanhe as redes sociais da prefeitura.',
                'contexto' => 'Agência do Trabalhador de Assaí: intermediação de vagas, seguro-desemprego.',
                'triggers' => [
                    'emprego', 'vaga', 'trabalho', 'agência do trabalhador', 'seguro desemprego',
                    'onde fica a agência do trabalhador', 'procurar emprego',
                ],
                'prioridade' => 83,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'trabalho', 'tags' => ['emprego', 'vagas', 'trabalho']],
            ],
            [
                'intencao_id' => 'conselho_tutelar',
                'resposta' => 'O <strong>Conselho Tutelar de Assaí</strong> zela pelo cumprimento dos direitos da criança e do adolescente. Endereço: Rua Equador, 427, Centro. Telefone: (43) 3262-1750. Em caso de violação de direitos, procure o conselho tutelar ou disque 100 (Disque Direitos Humanos).',
                'contexto' => 'Conselho Tutelar de Assaí: proteção de crianças e adolescentes.',
                'triggers' => [
                    'conselho tutelar', 'criança', 'adolescente', 'violação de direitos',
                    'onde fica o conselho tutelar', 'telefone conselho tutelar',
                ],
                'prioridade' => 81,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'social', 'tags' => ['conselho tutelar', 'proteção']],
            ],
            [
                'intencao_id' => 'coordenadoria_mulher',
                'resposta' => 'A <strong>Coordenadoria da Mulher</strong> de Assaí desenvolve políticas públicas voltadas para as mulheres, como orientação jurídica, psicológica e social, além de campanhas de enfrentamento à violência doméstica. Para atendimento, procure a Secretaria de Assistência Social ou ligue para (43) 3262-1223.',
                'contexto' => 'Coordenadoria da Mulher: políticas para mulheres, apoio em violência doméstica.',
                'triggers' => [
                    'coordenadoria da mulher', 'violência doméstica', 'mulher', 'feminicídio', 'políticas para mulheres',
                    'onde atende a coordenadoria da mulher',
                ],
                'prioridade' => 75,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'social', 'tags' => ['mulher', 'coordenadoria']],
            ],
            [
                'intencao_id' => 'procon',
                'resposta' => 'O <strong>PROCON Municipal de Assaí</strong> é o órgão de defesa do consumidor. Você pode registrar reclamações sobre produtos e serviços, buscar orientação e solicitar audiências de conciliação. Verifique o canal específico no <a href="https://www.assai.pr.gov.br" target="_blank">site da Prefeitura</a> ou entre em contato pelo telefone da Secretaria de Finanças: (43) 3262-1313.',
                'contexto' => 'PROCON Municipal de Assaí: defesa do consumidor.',
                'triggers' => [
                    'procon', 'consumidor', 'reclamação de serviço', 'direito do consumidor',
                    'onde fica o procon', 'procon municipal',
                ],
                'prioridade' => 74,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'atendimento', 'tags' => ['procon', 'consumidor']],
            ],
            [
                'intencao_id' => 'junta_militar',
                'resposta' => 'A <strong>Junta de Serviço Militar de Assaí</strong> é responsável pelo alistamento militar obrigatório (jovens que completam 18 anos). O alistamento pode ser feito online pelo site <a href="https://www.alistamento.eb.mil.br" target="_blank">alistamento.eb.mil.br</a> ou presencialmente na Junta, localizada no Paço Municipal (Av. Rio de Janeiro, 720). Telefone: (43) 3262-1313.',
                'contexto' => 'Junta de Serviço Militar de Assaí. Alistamento online ou presencial.',
                'triggers' => [
                    'junta militar', 'alistamento', 'serviço militar', 'exército', 'reservista',
                    'onde fica a junta militar', 'alistamento militar obrigatório',
                ],
                'prioridade' => 78,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'cidadania', 'tags' => ['militar', 'alistamento']],
            ],
            [
                'intencao_id' => 'e_sic',
                'resposta' => 'O <strong>e-SIC (Serviço de Informação ao Cidadão)</strong> é a ferramenta para solicitar informações públicas com base na Lei de Acesso à Informação. Acesse o <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> e localize o serviço "E-SIC" para fazer seu pedido, acompanhar o protocolo e receber a resposta no prazo legal.',
                'contexto' => 'e-SIC: Serviço de Informação ao Cidadão de Assaí. Lei de Acesso à Informação.',
                'triggers' => [
                    'e-sic', 'acesso à informação', 'lei de acesso', 'transparência ativa',
                    'pedir informação pública', 'sic',
                ],
                'prioridade' => 70,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'transparência', 'tags' => ['e-sic', 'informação']],
            ],
            [
                'intencao_id' => 'defesa_civil',
                'resposta' => 'A <strong>Defesa Civil de Assaí</strong> atua na prevenção e resposta a desastres naturais. Em caso de emergência, ligue 199. Para receber alertas, acesse o serviço no <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a>. O município possui 11 áreas de atenção mapeadas pela Defesa Civil.',
                'contexto' => 'Defesa Civil de Assaí: emergências, alertas, prevenção de desastres.',
                'triggers' => [
                    'defesa civil', 'desastre', 'inundação', 'alagamento', 'emergência climática',
                    'telefone da defesa civil', 'onde fica a defesa civil',
                ],
                'prioridade' => 79,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'segurança', 'tags' => ['defesa civil', 'emergência']],
            ],
            [
                'intencao_id' => 'guarda_municipal',
                'resposta' => 'A <strong>Guarda Civil Municipal de Assaí</strong> foi criada pela Lei Municipal nº 1.922/2025 e atua na proteção de bens, serviços e instalações públicas municipais. A sede está localizada na Rua Brasil, próximo ao Bombeiro Comunitário. Em situações de emergência, ligue 153.',
                'contexto' => 'Guarda Civil Municipal de Assaí: proteção do patrimônio público.',
                'triggers' => [
                    'guarda municipal', 'guarda civil', 'gcm', 'segurança pública',
                    'telefone guarda municipal', 'sede guarda municipal',
                ],
                'prioridade' => 75,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'segurança', 'tags' => ['guarda municipal', 'segurança']],
            ],
            [
                'intencao_id' => 'policia_civil',
                'resposta' => 'A <strong>Polícia Civil de Assaí</strong> atende na Delegacia de Polícia, localizada na Rua Brasil, 889, Centro. Telefone: (43) 3262-1441. Para registros de ocorrências não emergenciais, você também pode utilizar a Delegacia Eletrônica no site da Polícia Civil do Paraná.',
                'contexto' => 'Polícia Civil de Assaí. Delegacia: Rua Brasil, 889. Tel: (43) 3262-1441.',
                'triggers' => [
                    'polícia civil', 'delegacia', 'boletim de ocorrência', 'investigação',
                    'onde fica a delegacia', 'telefone delegacia',
                ],
                'prioridade' => 73,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'segurança', 'tags' => ['polícia civil', 'delegacia']],
            ],
            [
                'intencao_id' => 'telefones_uteis',
                'resposta' => 'Telefones úteis de Assaí:<ul><li><strong>Prefeitura:</strong> (43) 3262-1313</li><li><strong>Hospital Municipal:</strong> (43) 3262-4080</li><li><strong>SAMU:</strong> 192</li><li><strong>Corpo de Bombeiros:</strong> 193</li><li><strong>Defesa Civil:</strong> 199</li><li><strong>Polícia Militar:</strong> 190</li><li><strong>Polícia Civil:</strong> (43) 3262-1441</li><li><strong>Guarda Municipal:</strong> 153</li><li><strong>Sanepar:</strong> 0800-200-0115</li><li><strong>Copel:</strong> 0800-51-00-116</li><li><strong>Detran:</strong> (43) 3262-1155</li><li><strong>Terminal Rodoviário:</strong> (43) 3262-1156</li><li><strong>Agência Vale do Sol:</strong> (43) 3262-8306</li></ul>',
                'contexto' => 'Lista de telefones úteis do município de Assaí.',
                'triggers' => [
                    'telefone', 'telefones', 'contato', 'emergência', 'hospital', 'samu', 'bombeiro', 'polícia', 'sanepar', 'copel', 'detran',
                    'telefone do detran', 'telefone da sanepar', 'telefone do hospital', 'número da prefeitura', 'central de atendimento', 'ligar para',
                ],
                'prioridade' => 74,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'contato', 'tags' => ['telefones', 'emergência', 'serviços']],
            ],
            [
                'intencao_id' => 'cnp_mei',
                'resposta' => 'Pelo <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> você pode:<ul><li>Emitir Extrato de Contribuição (CNIS)</li><li>Consultar CPF na Receita Federal</li><li>Emitir GPS para pagamento de INSS</li><li>Obter o Certificado de Direito à Assistência Médica (CDAM/PB4)</li><li>Realizar a baixa do CNPJ de MEI</li><li><a href="https://conecta.assai.pr.gov.br/servico/34" target="_blank">Baixar CNPJ MEI</a></li></ul>',
                'contexto' => 'Serviços digitais disponíveis no Conecta Assaí: CNIS, CPF, GPS, CDAM, baixa MEI.',
                'triggers' => [
                    'mei', 'cnpj', 'cpf', 'inss', 'gps', 'cnis', 'pb4',
                    'baixar cnpj mei', 'extrato cnis', 'serviços mei',
                ],
                'prioridade' => 82,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'serviços', 'tags' => ['mei', 'digital']],
            ],
            [
                'intencao_id' => 'mei_cadastrar',
                'resposta' => 'Para se formalizar como <strong>Microempreendedor Individual (MEI)</strong>, acesse o <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> e utilize o serviço "Cadastrar MEI". O processo é online e gratuito. Você precisará do CPF, título de eleitor (ou declaração de imposto de renda) e endereço residencial/fiscal.',
                'contexto' => 'Cadastrar MEI em Assaí. Serviço disponível no Conecta Assaí.',
                'triggers' => [
                    'cadastrar mei', 'abrir mei', 'virar mei', 'formalizar mei',
                    'como abrir mei', 'registrar mei',
                ],
                'prioridade' => 91,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'mei', 'tags' => ['mei', 'cadastro']],
            ],
            [
                'intencao_id' => 'mei_ccei',
                'resposta' => 'O <strong>CCMEI (Certificado da Condição de Microempreendedor Individual)</strong> pode ser emitido gratuitamente no <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a>. Basta acessar o serviço "Emitir CCMEI" e informar o CNPJ. O documento comprova a formalização do MEI.',
                'contexto' => 'Emitir CCMEI (Certificado de MEI) no Conecta Assaí.',
                'triggers' => [
                    'ccei', 'ccmei', 'certificado mei', 'comprovante mei',
                    'emitir ccmei', 'tirar certificado mei',
                ],
                'prioridade' => 90,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'mei', 'tags' => ['mei', 'certificado']],
            ],
            [
                'intencao_id' => 'mei_atualizar',
                'resposta' => 'Para <strong>atualizar os dados cadastrais do MEI</strong> (endereço, atividades, contatos), acesse o <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> e utilize a opção "Atualizar dados MEI". As alterações são enviadas automaticamente à Receita Federal.',
                'contexto' => 'Atualizar dados do MEI pelo Conecta Assaí.',
                'triggers' => [
                    'alterar mei', 'atualizar mei', 'mudar endereço mei', 'modificar atividades mei',
                    'atualização mei', 'corrigir dados mei',
                ],
                'prioridade' => 89,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'mei', 'tags' => ['mei', 'atualização']],
            ],
            [
                'intencao_id' => 'mei_parcelar',
                'resposta' => 'Se você possui <strong>débitos em atraso como MEI</strong>, pode parcelá-los diretamente pelo <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a>. Procure pelo serviço "Parcelar dívidas do MEI". O parcelamento permite regularizar sua situação e continuar usufruindo dos benefícios previdenciários.',
                'contexto' => 'Parcelamento de dívidas do MEI no Conecta Assaí.',
                'triggers' => [
                    'parcelar mei', 'negociar dívida mei', 'débitos mei', 'regularizar mei',
                    'parcelamento mei', 'como pagar dívida mei',
                ],
                'prioridade' => 88,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'mei', 'tags' => ['mei', 'parcelamento']],
            ],
            [
                'intencao_id' => 'mei_das',
                'resposta' => 'A Guia <strong>DAS (Documento de Arrecadação do Simples Nacional)</strong> do MEI pode ser emitida mensalmente pelo <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> no serviço "Emitir DAS". O pagamento deve ser feito até o dia 20 de cada mês para garantir a cobertura previdenciária.',
                'contexto' => 'Emitir DAS do MEI pelo Conecta Assaí.',
                'triggers' => [
                    'das', 'documento de arrecadação', 'guia das', 'mensalidade mei',
                    'emitir das', 'pagamento das',
                ],
                'prioridade' => 89,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'mei', 'tags' => ['mei', 'das']],
            ],
            [
                'intencao_id' => 'sala_empreendedor',
                'resposta' => 'A <strong>Sala do Empreendedor Digital</strong> de Assaí reúne todos os serviços para MEIs e empresas: cadastro, emissão de boletos, declaração anual, certidões e notas fiscais. Acesse pelo <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> e procure por "Sala do Empreendedor".',
                'contexto' => 'Sala do Empreendedor Digital de Assaí. Disponível no Conecta Assaí.',
                'triggers' => [
                    'sala do empreendedor', 'empreendedor', 'empresa', 'negócio',
                    'onde fica a sala do empreendedor', 'serviços para empreendedor',
                ],
                'prioridade' => 87,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'empresas', 'tags' => ['empreendedor', 'mei']],
            ],
            [
                'intencao_id' => 'iptu',
                'resposta' => 'O <strong>IPTU (Imposto Predial e Territorial Urbano)</strong> é administrado pela <strong>Secretaria de Finanças</strong> da Prefeitura de Assaí. Para emissão de 2ª via, informações sobre parcelamento ou isenção, acesse o <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> ou compareça ao setor de tributação na Av. Rio de Janeiro, 720, das 8h às 11h30 e das 13h às 17h.',
                'contexto' => 'IPTU de Assaí. Emissão de guias, parcelamento, isenção.',
                'triggers' => [
                    'iptu', 'imposto predial', 'imposto territorial', 'tributo', 'guia iptu',
                    '2ª via iptu', 'segunda via iptu', 'pagar iptu', 'parcelamento iptu', 'isenção iptu', 'onde pagar iptu',
                ],
                'prioridade' => 86,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'tributos', 'tags' => ['iptu', 'imposto']],
            ],
            [
                'intencao_id' => 'itbi',
                'resposta' => 'O <strong>ITBI (Imposto sobre Transmissão de Bens Imóveis)</strong> é cobrado na compra e venda de imóveis. A guia de recolhimento pode ser emitida no setor de tributação da <strong>Secretaria de Finanças</strong>, na Av. Rio de Janeiro, 720, ou pelo <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a>. O ITBI é calculado sobre o valor venal do imóvel.',
                'contexto' => 'ITBI: imposto de transmissão de imóveis. Emissão pela Secretaria de Finanças.',
                'triggers' => [
                    'itbi', 'imposto de transmissão', 'compra de imóvel', 'escritura',
                    'guia itbi', 'pagar itbi',
                ],
                'prioridade' => 80,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'tributos', 'tags' => ['itbi', 'imposto']],
            ],
            [
                'intencao_id' => 'iss',
                'resposta' => 'O <strong>ISS (Imposto Sobre Serviços)</strong> incide sobre a prestação de serviços. A guia de ISS pode ser emitida pelo <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a>. Profissionais autônomos e empresas devem manter o recolhimento em dia. Para dúvidas, procure a Secretaria de Finanças pelo telefone (43) 3262-1313.',
                'contexto' => 'ISS: Imposto Sobre Serviços. Emissão de guia no Conecta Assaí.',
                'triggers' => [
                    'iss', 'imposto sobre serviços', 'issqn', 'guia iss',
                    'pagar iss', 'imposto de serviço',
                ],
                'prioridade' => 81,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'tributos', 'tags' => ['iss', 'imposto']],
            ],
            [
                'intencao_id' => 'guia_unificada',
                'resposta' => 'A <strong>Guia Unificada</strong> da Prefeitura de Assaí reúne IPTU, ISS e taxas diversas em um único boleto. A emissão pode ser feita online pelo <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a>. Caso não conste, entre em contato com a Secretaria de Finanças.',
                'contexto' => 'Guia unificada de tributos municipais (IPTU, ISS, taxas).',
                'triggers' => [
                    'guia unificada', 'boleto único', 'tributo municipal', 'taxas',
                    'emitir guia unificada', 'guia de pagamento unificada',
                ],
                'prioridade' => 79,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'tributos', 'tags' => ['guia', 'unificada']],
            ],
            [
                'intencao_id' => 'nfe_municipal',
                'resposta' => 'A <strong>Nota Fiscal Eletrônica de Serviços (NFS-e)</strong> em Assaí é emitida através do sistema da prefeitura. Acesse o <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> e procure por "Nota Fiscal Eletrônica" ou acesse o link específico disponível no portal da Sala do Empreendedor. Para suporte, contate a Secretaria de Finanças.',
                'contexto' => 'NFS-e municipal: emissão de nota fiscal eletrônica.',
                'triggers' => [
                    'nota fiscal', 'nfe', 'nfs-e', 'nota eletrônica',
                    'emitir nota fiscal', 'nota fiscal eletrônica de serviço',
                ],
                'prioridade' => 83,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'empresas', 'tags' => ['nota fiscal', 'nfe']],
            ],
            [
                'intencao_id' => 'matricula_escolar',
                'resposta' => 'As matrículas na <strong>rede municipal de ensino de Assaí</strong> são organizadas pela Secretaria Municipal de Educação. O período de matrícula é divulgado anualmente no site oficial e nas escolas. Para informações sobre vagas, documentação e prazos, ligue para a Secretaria de Educação no (43) 3262-1240.',
                'contexto' => 'Matrícula escolar na rede municipal. Secretaria de Educação: (43) 3262-1240.',
                'triggers' => [
                    'matrícula', 'matrícula escolar', 'matricular filho', 'vaga na escola',
                    'como matricular', 'onde fazer matrícula',
                ],
                'prioridade' => 85,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'educação', 'tags' => ['matrícula', 'escola']],
            ],
            [
                'intencao_id' => 'transporte_escolar',
                'resposta' => 'O <strong>transporte escolar</strong> gratuito é oferecido aos alunos da rede municipal e estadual que residem em áreas rurais ou distantes da escola. Para solicitar, procure a Secretaria de Educação (tel: (43) 3262-1240) ou a direção da escola onde o aluno está matriculado.',
                'contexto' => 'Transporte escolar gratuito em Assaí.',
                'triggers' => [
                    'transporte escolar', 'ônibus escolar', 'condução escolar', 'passe escolar',
                    'como solicitar transporte escolar',
                ],
                'prioridade' => 82,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'educação', 'tags' => ['transporte', 'escolar']],
            ],
            [
                'intencao_id' => 'cmeis',
                'resposta' => 'Os <strong>Centros Municipais de Educação Infantil (CMEIs)</strong> atendem crianças de 0 a 5 anos em período integral ou parcial. A lista de CMEIs e informações sobre vagas podem ser obtidas na Secretaria de Educação, pelo telefone (43) 3262-1240.',
                'contexto' => 'CMEIs de Assaí: educação infantil.',
                'triggers' => [
                    'cmei', 'creche', 'educação infantil', 'criança pequena',
                    'onde matricular criança pequena', 'vagas creche',
                ],
                'prioridade' => 83,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'educação', 'tags' => ['cmei', 'educação infantil']],
            ],
            [
                'intencao_id' => 'ensino_bilingue',
                'resposta' => 'Assaí conta com o programa <strong>"Assaí, um futuro bilíngue"</strong>, que oferece aulas de inglês e japonês na rede municipal de ensino. A iniciativa é coordenada pela Secretaria de Educação. Para saber mais, ligue (43) 3262-1240.',
                'contexto' => 'Programa de ensino bilíngue (inglês e japonês) da rede municipal.',
                'triggers' => [
                    'bilíngue', 'inglês', 'japonês', 'ensino bilíngue',
                    'aulas de inglês', 'aulas de japonês',
                ],
                'prioridade' => 78,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'educação', 'tags' => ['bilíngue', 'idiomas']],
            ],
            [
                'intencao_id' => 'oficinas_extracurriculares',
                'resposta' => 'A Secretaria de Educação oferece <strong>oficinas extracurriculares</strong> no contraturno escolar, incluindo robótica, xadrez, fanfarra e reforço escolar. As inscrições acontecem no início do ano letivo. Informe-se na escola do seu filho ou ligue (43) 3262-1240.',
                'contexto' => 'Oficinas extracurriculares da rede municipal: robótica, xadrez, fanfarra.',
                'triggers' => [
                    'oficinas', 'contraturno', 'robótica', 'xadrez', 'fanfarra', 'reforço',
                    'inscrição oficinas', 'atividades extracurriculares',
                ],
                'prioridade' => 77,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'educação', 'tags' => ['oficinas', 'extracurricular']],
            ],
            [
                'intencao_id' => 'historico_escolar',
                'resposta' => 'Para solicitar a <strong>2ª via do Histórico Escolar</strong> da rede municipal, procure a Secretaria de Educação de Assaí ou a escola onde você estudou. Mais informações pelo telefone (43) 3262-1240.',
                'contexto' => '2ª via de histórico escolar. Secretaria de Educação.',
                'triggers' => [
                    'histórico escolar', '2ª via', 'documento escolar',
                    'pedir histórico escolar', 'segunda via histórico',
                ],
                'prioridade' => 76,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'educação', 'tags' => ['histórico', 'documento']],
            ],
            [
                'intencao_id' => 'castelo_japones',
                'resposta' => 'O <strong>Castelo Japonês</strong> é a sede da Secretaria de Cultura e Turismo (SECUT) e abriga o <strong>Memorial da Imigração Japonesa</strong>. Endereço: Avenida Rio de Janeiro, s/n. Telefone: (43) 3262-3232. Aberto à visitação durante a semana. Uma atração turística que celebra a história dos imigrantes japoneses em Assaí.',
                'contexto' => 'Castelo Japonês: memorial e sede da SECUT. Tel: (43) 3262-3232.',
                'triggers' => [
                    'castelo japonês', 'castelo', 'memorial da imigração', 'sede da cultura',
                    'onde fica o castelo japonês', 'visitar castelo',
                ],
                'prioridade' => 77,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'turismo', 'tags' => ['castelo', 'imigração']],
            ],
            [
                'intencao_id' => 'parque_ikeda',
                'resposta' => 'O <strong>Parque Ikeda</strong> é uma área de lazer com pista de caminhada, skate park, campo de bocha e parque infantil. Fica em Assaí e é um espaço público para toda a família. Para informações sobre horários e eventos, consulte a SECUT pelo telefone (43) 3262-3232.',
                'contexto' => 'Parque Ikeda: lazer, caminhada, skate, parque infantil.',
                'triggers' => [
                    'parque ikeda', 'parque', 'lazer', 'caminhada', 'skate',
                    'onde fica o parque ikeda', 'parque infantil assaí',
                ],
                'prioridade' => 74,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'turismo', 'tags' => ['parque', 'lazer']],
            ],
            [
                'intencao_id' => 'museu_imigracao',
                'resposta' => 'O <strong>Museu da Imigração Japonesa</strong> funciona dentro do Castelo Japonês e reúne objetos, fotos e documentos que contam a história da colonização japonesa em Assaí. Visitação de segunda a sexta, em horário comercial. Mais informações: SECUT (43) 3262-3232.',
                'contexto' => 'Museu da Imigração Japonesa, no Castelo Japonês.',
                'triggers' => [
                    'museu', 'museu da imigração', 'imigração japonesa', 'história',
                    'onde fica o museu', 'visitar museu da imigração',
                ],
                'prioridade' => 75,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'turismo', 'tags' => ['museu', 'história']],
            ],
            [
                'intencao_id' => 'feira_livro',
                'resposta' => 'A <strong>Feira do Livro de Assaí</strong> é um evento anual que reúne editoras, autores, apresentações culturais e atividades para todas as idades. Acontece geralmente no segundo semestre. Acompanhe as datas no site oficial <a href="https://www.assai.pr.gov.br" target="_blank">www.assai.pr.gov.br</a>.',
                'contexto' => 'Feira do Livro: evento literário anual de Assaí.',
                'triggers' => [
                    'feira do livro', 'feira literária', 'livros', 'literatura',
                    'quando é a feira do livro', 'evento literário',
                ],
                'prioridade' => 72,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'eventos', 'tags' => ['feira', 'livro']],
            ],
            [
                'intencao_id' => 'eventos_culturais',
                'resposta' => 'Assaí realiza diversos eventos culturais durante o ano: <strong>Bon Odori (Festival da Primavera)</strong>, <strong>Matsuri Dance</strong>, <strong>Festa do Peão</strong>, shows e apresentações artísticas. Para saber a programação atualizada, acesse o site da prefeitura ou siga a SECUT nas redes sociais. Telefone para informações: (43) 3262-3232.',
                'contexto' => 'Eventos culturais de Assaí: Bon Odori, Matsuri Dance, Festa do Peão.',
                'triggers' => [
                    'bon odori', 'matsuri', 'festival', 'festa do peão', 'show', 'evento cultural',
                    'próximos eventos', 'agenda cultural',
                ],
                'prioridade' => 76,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'eventos', 'tags' => ['cultura', 'festival']],
            ],
            [
                'intencao_id' => 'redes_sociais',
                'resposta' => 'Acompanhe a Prefeitura de Assaí nas redes sociais: <a href="https://www.instagram.com/prefeituradeassai" target="_blank">Instagram @prefeituradeassai</a>, <a href="https://www.facebook.com/prefeituradeassai" target="_blank">Facebook /prefeituradeassai</a> e <a href="https://www.youtube.com/@prefeituradeassai" target="_blank">YouTube Prefeitura de Assaí</a>. Lá são divulgadas notícias, editais e eventos.',
                'contexto' => 'Redes sociais oficiais: Instagram, Facebook, YouTube.',
                'triggers' => [
                    'instagram', 'facebook', 'youtube', 'redes sociais', 'mídias sociais',
                    'seguir prefeitura', 'redes da prefeitura',
                ],
                'prioridade' => 68,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'comunicação', 'tags' => ['redes', 'social']],
            ],
            [
                'intencao_id' => 'whatsapp_ubs',
                'resposta' => 'As <strong>Unidades Básicas de Saúde de Assaí</strong> disponibilizam números de WhatsApp para agendamento de consultas e informações. Os números específicos de cada UBS podem ser consultados no site oficial da prefeitura (seção Saúde) ou ligando para a Secretaria de Saúde: (43) 3262-8405.',
                'contexto' => 'WhatsApp das UBS para agendamento. Consulte site ou ligue (43) 3262-8405.',
                'triggers' => [
                    'whatsapp', 'zap da saúde', 'agendamento whatsapp', 'whatsapp ubs',
                    'consultar whatsapp ubs',
                ],
                'prioridade' => 71,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'saúde', 'tags' => ['whatsapp', 'ubs']],
            ],
            [
                'intencao_id' => 'leis_municipais',
                'resposta' => 'As <strong>leis municipais de Assaí</strong> podem ser consultadas no site da prefeitura, na seção "Legislação" (geralmente em assai.pr.gov.br/legislacao) ou através do <a href="https://www.doemunicipal.com.br/prefeituras/4" target="_blank">Diário Oficial Eletrônico</a>. Lá você encontra leis, decretos e portarias.',
                'contexto' => 'Leis municipais de Assaí: site oficial ou Diário Oficial.',
                'triggers' => [
                    'leis', 'legislação municipal', 'código de posturas', 'lei orgânica',
                    'onde consultar leis', 'legislação',
                ],
                'prioridade' => 70,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'documentos', 'tags' => ['leis', 'legislação']],
            ],
            [
                'intencao_id' => 'planos_municipio',
                'resposta' => 'Os principais planos do município, como o <strong>Plano Diretor</strong>, <strong>Plano Plurianual (PPA)</strong>, <strong>Lei de Diretrizes Orçamentárias (LDO)</strong> e <strong>Lei Orçamentária Anual (LOA)</strong> estão disponíveis no Portal da Transparência (<a href="https://transparencia.betha.cloud" target="_blank">transparencia.betha.cloud</a>) e no site oficial da prefeitura.',
                'contexto' => 'Planos municipais: Plano Diretor, PPA, LDO, LOA.',
                'triggers' => [
                    'plano diretor', 'plano de governo', 'ppa', 'ldo', 'loa', 'planejamento',
                    'consultar planos municipais', 'onde ver plano diretor',
                ],
                'prioridade' => 69,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'documentos', 'tags' => ['planos', 'orçamento']],
            ],
            [
                'intencao_id' => 'livro_eletronico',
                'resposta' => 'O <strong>Livro Eletrônico</strong> reúne as publicações oficiais da Prefeitura em formato digital. Acesse pelo <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> ou procure no site oficial a seção correspondente. É uma ferramenta que substitui a papeleta tradicional.',
                'contexto' => 'Livro Eletrônico: publicações oficiais digitais.',
                'triggers' => [
                    'livro eletrônico', 'livro digital', 'publicações eletrônicas',
                    'acessar livro eletrônico', 'papeleta digital',
                ],
                'prioridade' => 68,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'documentos', 'tags' => ['livro', 'eletrônico']],
            ],
            [
                'intencao_id' => 'editais',
                'resposta' => 'Para consultar editais e inscrições abertas em Assaí, acesse o <a href="https://conecta.assai.pr.gov.br" target="_blank">Conecta Assaí</a> na seção "Inscrições Abertas". Exemplos de editais recentes: Processo Seletivo para Estágio no Município, Cadastro de Cidadão Externo e Solicitação de Uso de Espaços da Agência de Inovação.',
                'contexto' => 'Editais e inscrições abertas no Conecta Assaí.',
                'triggers' => [
                    'edital', 'inscrição', 'processo seletivo', 'concurso público', 'estágio',
                    'ver editais abertos', 'inscrições abertas',
                ],
                'prioridade' => 81,
                'uso_count' => 0,
                'ativa' => true,
                'metadata' => ['categoria' => 'serviços', 'tags' => ['editais', 'concursos']],
            ],
        ];

        foreach ($intencoes as $intencao) {
            Intencao::updateOrCreate(
                ['intencao_id' => $intencao['intencao_id']],
                $intencao
            );
        }
    }
}